config/routes.rb
Rails.application.routes.draw do
  # resources :pages
  # get "states/index"
  # get "states/show"
  # get "home/index"
  resources :pages, except: [:show]

  get "/pages/:permalink" => "pages#permalink", as: :permalink
  resources :universities
  resources :states, only: %i[index show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
  validates :name, presence: true
  has_many :universities, through: :university_programs
end

app/models/state.rb
class State < ApplicationRecord
  validates :state, :latitude, :name, :longitude, presence: true
  validates :state, :name, uniqueness: true
  has_many :universities
end

app/models/university.rb
class University < ApplicationRecord
  validates :name, :city, :zip, presence: true
  validates :name, uniqueness: true
  belongs_to :state
  has_many :programs, through: :university_programs
end

app/models/university_program.rb
class UniversityProgram < ApplicationRecord
  belongs_to :university
  belongs_to :program
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @universities = University.all.limit(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # http_basic_authenticate_with name: "admin", password: "admin", except: [:permalink]
  # before_action :set_page, only: %i[show edit update destroy]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  # def show; end

  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
  end

  def show
    @state = State.find(params[:id])
  end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: %i[show edit update destroy]

  # GET /universities or /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1 or /universities/1.json
  def show
    @university = University.find(params[:id])
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit; end

  # POST /universities or /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html do
          redirect_to university_url(@university), notice: "University was successfully created."
        end
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1 or /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html do
          redirect_to university_url(@university), notice: "University was successfully updated."
        end
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1 or /universities/1.json
  def destroy
    @university.destroy

    respond_to do |format|
      format.html { redirect_to universities_url, notice: "University was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_university
    @university = University.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def university_params
    params.require(:university).permit(:name, :rank, :photo, :zip, :state, :city, :program)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <ul class="mt-5">
    <li><%= link_to 'Home', root_path %></li>
  </ul>
</footer>

app/views/home/index.html.erb
<h1>Us Univerisites</h1>

<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top Us Univerisites</h2>
    <ol class="ml-5">
      <% @universities.each do |uni| %>
        <li>
          <%= link_to uni.name, uni %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Us Universities</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <% if controller_name =='home'%>
      <p>Copyright 2022 RRC</p>
    <% else %>
      <%=render partial: "common/footer" %>
    <% end %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4">
  <%= @page.title %>
</h2>

<p class="mt-5">
  <%= @page.content %>
</p>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/states/index.html.erb
<h1>States#index</h1>
<p>Find me in app/views/states/index.html.erb</p>

app/views/states/show.html.erb
<h2 class="title is-2"><%= @state.name %></h2>


<div class="content">
  <ul>
    <% @state.universities.each do |uni| %>
      <li>
        <%= link_to uni.name, uni %>
      </li>
    <% end %>
  </ul>
</div>

app/views/universities/_form.html.erb
<%= form_with(model: university) do |form| %>
  <% if university.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
        <% university.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rank, style: "display: block" %>
    <%= form.text_field :rank %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :program, style: "display: block" %>
    <%= form.text_field :program %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/universities/_university.html.erb
<div id="<%= dom_id university %>">
  <p>
    <strong>Name:</strong>
    <%= university.name %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= university.rank %>
  </p>

  <p>
    <strong>Photo:</strong>
    <img src=<%= university.photo %> alt=<%= university.name %>>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= university.zip %>
  </p>

  <p>
    <strong>State:</strong>
    <%= link_to university.state.state, university.state %>
  </p>

  <p>
    <strong>City:</strong>
    <%= university.city %>
  </p>

  <p>
    <strong>Program:</strong>
    <%= university.program %>
  </p>

</div>

app/views/universities/edit.html.erb
<h1>Editing university</h1>

<%= render "form", university: @university %>

<br>

<div>
  <%= link_to "Show this university", @university %> |
  <%= link_to "Back to universities", universities_path %>
</div>

app/views/universities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Universities</h1>

<div id="universities">
  <% @universities.each do |university| %>
    <%= render university %>
    <p>
      <%= link_to "Show this university", university %>
    </p>
  <% end %>
</div>

<%= link_to "New university", new_university_path %>

app/views/universities/new.html.erb
<h1>New university</h1>

<%= render "form", university: @university %>

<br>

<div>
  <%= link_to "Back to universities", universities_path %>
</div>

app/views/universities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @university %>

<div>
  <%= link_to "Edit this university", edit_university_path(@university) %> |
  <%= link_to "Back to universities", universities_path %>

  <%= button_to "Destroy this university", @university, method: :delete %>
</div>